### PR TITLE
ssl cert verification

### PR DESCRIPTION
**Pull request by eandtsa**
Hello,

Please approve a DataScript for SSL cert validation

### CODE REVIEW

**Comment by smarunich** [comment]
Please follow the example: https://github.com/avinetworks/datascript-library/blob/master/security/saml_attrs.md, add description/title plus update readme.md

**Comment by eandtsa** [comment]
Change added
Please check.

**Comment by smarunich** [comment]
Please update README.md file as well to list the script

**Comment by eandtsa** [comment]
Readme.RD updated
under Security

**Pull request merged**
